import 'package:baseer/features/distance_estimation/domain/object_size_prior.dart';
import 'package:baseer/features/object_detection/domain/coco_labels.dart';

class ObjectSizePriorDatabase {
  final Map<String, ObjectSizePrior> _priors;

  const ObjectSizePriorDatabase._(this._priors);

  factory ObjectSizePriorDatabase.coco80() {
    final priors = <String, ObjectSizePrior>{};
    for (final label in cocoClassNames) {
      priors[label] = _overrides[label] ?? _defaultFor(label);
    }
    return ObjectSizePriorDatabase._(priors);
  }

  ObjectSizePrior getPrior(String label) =>
      _priors[label] ?? _defaultFor(label);

  static ObjectSizePrior _defaultFor(String label) {
    return ObjectSizePrior(
      className: label,
      typicalHeightM: 1.0,
      typicalWidthM: 0.5,
      heightStdM: 0.4,
      widthStdM: 0.4,
      heightConfidence: 0.2,
      widthConfidence: 0.2,
    );
  }
}

const Map<String, ObjectSizePrior> _overrides = {
  'person': ObjectSizePrior(
    className: 'person',
    typicalHeightM: 1.70,
    typicalWidthM: 0.45,
    heightStdM: 0.12,
    widthStdM: 0.10,
    heightConfidence: 0.85,
    widthConfidence: 0.60,
  ),
  'bicycle': ObjectSizePrior(
    className: 'bicycle',
    typicalHeightM: 1.10,
    typicalWidthM: 1.70,
    heightStdM: 0.08,
    widthStdM: 0.15,
    heightConfidence: 0.80,
    widthConfidence: 0.65,
  ),
  'car': ObjectSizePrior(
    className: 'car',
    typicalHeightM: 1.50,
    typicalWidthM: 1.80,
    heightStdM: 0.15,
    widthStdM: 0.30,
    heightConfidence: 0.75,
    widthConfidence: 0.70,
  ),
  'motorcycle': ObjectSizePrior(
    className: 'motorcycle',
    typicalHeightM: 1.20,
    typicalWidthM: 2.00,
    heightStdM: 0.10,
    widthStdM: 0.20,
    heightConfidence: 0.75,
    widthConfidence: 0.65,
  ),
  'airplane': ObjectSizePrior(
    className: 'airplane',
    typicalHeightM: 4.50,
    typicalWidthM: 30.0,
    heightStdM: 1.50,
    widthStdM: 8.00,
    heightConfidence: 0.35,
    widthConfidence: 0.35,
  ),
  'bus': ObjectSizePrior(
    className: 'bus',
    typicalHeightM: 3.00,
    typicalWidthM: 2.50,
    heightStdM: 0.30,
    widthStdM: 0.40,
    heightConfidence: 0.80,
    widthConfidence: 0.70,
  ),
  'train': ObjectSizePrior(
    className: 'train',
    typicalHeightM: 3.80,
    typicalWidthM: 3.00,
    heightStdM: 0.60,
    widthStdM: 0.40,
    heightConfidence: 0.70,
    widthConfidence: 0.60,
  ),
  'truck': ObjectSizePrior(
    className: 'truck',
    typicalHeightM: 2.50,
    typicalWidthM: 2.40,
    heightStdM: 0.50,
    widthStdM: 0.60,
    heightConfidence: 0.60,
    widthConfidence: 0.60,
  ),
  'boat': ObjectSizePrior(
    className: 'boat',
    typicalHeightM: 1.80,
    typicalWidthM: 4.50,
    heightStdM: 0.60,
    widthStdM: 1.50,
    heightConfidence: 0.50,
    widthConfidence: 0.50,
  ),
  'traffic light': ObjectSizePrior(
    className: 'traffic light',
    typicalHeightM: 0.80,
    typicalWidthM: 0.25,
    heightStdM: 0.10,
    widthStdM: 0.05,
    heightConfidence: 0.80,
    widthConfidence: 0.70,
  ),
  'fire hydrant': ObjectSizePrior(
    className: 'fire hydrant',
    typicalHeightM: 0.60,
    typicalWidthM: 0.30,
    heightStdM: 0.06,
    widthStdM: 0.04,
    heightConfidence: 0.85,
    widthConfidence: 0.75,
  ),
  'stop sign': ObjectSizePrior(
    className: 'stop sign',
    typicalHeightM: 0.75,
    typicalWidthM: 0.75,
    heightStdM: 0.05,
    widthStdM: 0.05,
    heightConfidence: 0.85,
    widthConfidence: 0.85,
  ),
  'parking meter': ObjectSizePrior(
    className: 'parking meter',
    typicalHeightM: 1.30,
    typicalWidthM: 0.35,
    heightStdM: 0.20,
    widthStdM: 0.10,
    heightConfidence: 0.70,
    widthConfidence: 0.55,
  ),
  'bench': ObjectSizePrior(
    className: 'bench',
    typicalHeightM: 0.90,
    typicalWidthM: 1.50,
    heightStdM: 0.10,
    widthStdM: 0.30,
    heightConfidence: 0.70,
    widthConfidence: 0.75,
  ),
  'bird': ObjectSizePrior(
    className: 'bird',
    typicalHeightM: 0.25,
    typicalWidthM: 0.30,
    heightStdM: 0.08,
    widthStdM: 0.10,
    heightConfidence: 0.45,
    widthConfidence: 0.45,
  ),
  'cat': ObjectSizePrior(
    className: 'cat',
    typicalHeightM: 0.30,
    typicalWidthM: 0.45,
    heightStdM: 0.10,
    widthStdM: 0.12,
    heightConfidence: 0.55,
    widthConfidence: 0.55,
  ),
  'dog': ObjectSizePrior(
    className: 'dog',
    typicalHeightM: 0.50,
    typicalWidthM: 0.60,
    heightStdM: 0.15,
    widthStdM: 0.20,
    heightConfidence: 0.65,
    widthConfidence: 0.65,
  ),
  'horse': ObjectSizePrior(
    className: 'horse',
    typicalHeightM: 1.60,
    typicalWidthM: 2.20,
    heightStdM: 0.25,
    widthStdM: 0.30,
    heightConfidence: 0.70,
    widthConfidence: 0.60,
  ),
  'sheep': ObjectSizePrior(
    className: 'sheep',
    typicalHeightM: 0.90,
    typicalWidthM: 1.10,
    heightStdM: 0.20,
    widthStdM: 0.25,
    heightConfidence: 0.60,
    widthConfidence: 0.60,
  ),
  'cow': ObjectSizePrior(
    className: 'cow',
    typicalHeightM: 1.50,
    typicalWidthM: 2.20,
    heightStdM: 0.30,
    widthStdM: 0.40,
    heightConfidence: 0.65,
    widthConfidence: 0.60,
  ),
  'elephant': ObjectSizePrior(
    className: 'elephant',
    typicalHeightM: 3.20,
    typicalWidthM: 4.50,
    heightStdM: 0.60,
    widthStdM: 0.80,
    heightConfidence: 0.60,
    widthConfidence: 0.55,
  ),
  'bear': ObjectSizePrior(
    className: 'bear',
    typicalHeightM: 1.50,
    typicalWidthM: 2.00,
    heightStdM: 0.35,
    widthStdM: 0.40,
    heightConfidence: 0.55,
    widthConfidence: 0.55,
  ),
  'zebra': ObjectSizePrior(
    className: 'zebra',
    typicalHeightM: 1.40,
    typicalWidthM: 2.20,
    heightStdM: 0.25,
    widthStdM: 0.35,
    heightConfidence: 0.60,
    widthConfidence: 0.60,
  ),
  'giraffe': ObjectSizePrior(
    className: 'giraffe',
    typicalHeightM: 4.80,
    typicalWidthM: 2.50,
    heightStdM: 0.80,
    widthStdM: 0.40,
    heightConfidence: 0.65,
    widthConfidence: 0.50,
  ),
  'backpack': ObjectSizePrior(
    className: 'backpack',
    typicalHeightM: 0.50,
    typicalWidthM: 0.35,
    heightStdM: 0.12,
    widthStdM: 0.10,
    heightConfidence: 0.60,
    widthConfidence: 0.60,
  ),
  'umbrella': ObjectSizePrior(
    className: 'umbrella',
    typicalHeightM: 1.00,
    typicalWidthM: 1.00,
    heightStdM: 0.20,
    widthStdM: 0.20,
    heightConfidence: 0.55,
    widthConfidence: 0.55,
  ),
  'handbag': ObjectSizePrior(
    className: 'handbag',
    typicalHeightM: 0.30,
    typicalWidthM: 0.40,
    heightStdM: 0.08,
    widthStdM: 0.10,
    heightConfidence: 0.55,
    widthConfidence: 0.55,
  ),
  'tie': ObjectSizePrior(
    className: 'tie',
    typicalHeightM: 0.90,
    typicalWidthM: 0.08,
    heightStdM: 0.10,
    widthStdM: 0.02,
    heightConfidence: 0.55,
    widthConfidence: 0.40,
  ),
  'suitcase': ObjectSizePrior(
    className: 'suitcase',
    typicalHeightM: 0.70,
    typicalWidthM: 0.45,
    heightStdM: 0.15,
    widthStdM: 0.12,
    heightConfidence: 0.65,
    widthConfidence: 0.60,
  ),
  'frisbee': ObjectSizePrior(
    className: 'frisbee',
    typicalHeightM: 0.03,
    typicalWidthM: 0.25,
    heightStdM: 0.01,
    widthStdM: 0.03,
    heightConfidence: 0.35,
    widthConfidence: 0.55,
  ),
  'skis': ObjectSizePrior(
    className: 'skis',
    typicalHeightM: 1.70,
    typicalWidthM: 0.20,
    heightStdM: 0.20,
    widthStdM: 0.05,
    heightConfidence: 0.55,
    widthConfidence: 0.40,
  ),
  'snowboard': ObjectSizePrior(
    className: 'snowboard',
    typicalHeightM: 1.50,
    typicalWidthM: 0.30,
    heightStdM: 0.20,
    widthStdM: 0.06,
    heightConfidence: 0.55,
    widthConfidence: 0.40,
  ),
  'sports ball': ObjectSizePrior(
    className: 'sports ball',
    typicalHeightM: 0.22,
    typicalWidthM: 0.22,
    heightStdM: 0.05,
    widthStdM: 0.05,
    heightConfidence: 0.50,
    widthConfidence: 0.50,
  ),
  'kite': ObjectSizePrior(
    className: 'kite',
    typicalHeightM: 0.80,
    typicalWidthM: 0.80,
    heightStdM: 0.20,
    widthStdM: 0.20,
    heightConfidence: 0.45,
    widthConfidence: 0.45,
  ),
  'baseball bat': ObjectSizePrior(
    className: 'baseball bat',
    typicalHeightM: 0.85,
    typicalWidthM: 0.07,
    heightStdM: 0.08,
    widthStdM: 0.02,
    heightConfidence: 0.55,
    widthConfidence: 0.40,
  ),
  'baseball glove': ObjectSizePrior(
    className: 'baseball glove',
    typicalHeightM: 0.30,
    typicalWidthM: 0.30,
    heightStdM: 0.06,
    widthStdM: 0.06,
    heightConfidence: 0.50,
    widthConfidence: 0.50,
  ),
  'skateboard': ObjectSizePrior(
    className: 'skateboard',
    typicalHeightM: 0.80,
    typicalWidthM: 0.20,
    heightStdM: 0.12,
    widthStdM: 0.04,
    heightConfidence: 0.50,
    widthConfidence: 0.45,
  ),
  'surfboard': ObjectSizePrior(
    className: 'surfboard',
    typicalHeightM: 2.10,
    typicalWidthM: 0.55,
    heightStdM: 0.25,
    widthStdM: 0.10,
    heightConfidence: 0.55,
    widthConfidence: 0.45,
  ),
  'tennis racket': ObjectSizePrior(
    className: 'tennis racket',
    typicalHeightM: 0.68,
    typicalWidthM: 0.28,
    heightStdM: 0.06,
    widthStdM: 0.04,
    heightConfidence: 0.55,
    widthConfidence: 0.45,
  ),
  'bottle': ObjectSizePrior(
    className: 'bottle',
    typicalHeightM: 0.25,
    typicalWidthM: 0.07,
    heightStdM: 0.05,
    widthStdM: 0.02,
    heightConfidence: 0.85,
    widthConfidence: 0.60,
  ),
  'wine glass': ObjectSizePrior(
    className: 'wine glass',
    typicalHeightM: 0.18,
    typicalWidthM: 0.08,
    heightStdM: 0.04,
    widthStdM: 0.02,
    heightConfidence: 0.65,
    widthConfidence: 0.55,
  ),
  'cup': ObjectSizePrior(
    className: 'cup',
    typicalHeightM: 0.10,
    typicalWidthM: 0.08,
    heightStdM: 0.03,
    widthStdM: 0.02,
    heightConfidence: 0.60,
    widthConfidence: 0.55,
  ),
  'fork': ObjectSizePrior(
    className: 'fork',
    typicalHeightM: 0.20,
    typicalWidthM: 0.03,
    heightStdM: 0.03,
    widthStdM: 0.01,
    heightConfidence: 0.45,
    widthConfidence: 0.35,
  ),
  'knife': ObjectSizePrior(
    className: 'knife',
    typicalHeightM: 0.22,
    typicalWidthM: 0.03,
    heightStdM: 0.03,
    widthStdM: 0.01,
    heightConfidence: 0.45,
    widthConfidence: 0.35,
  ),
  'spoon': ObjectSizePrior(
    className: 'spoon',
    typicalHeightM: 0.18,
    typicalWidthM: 0.04,
    heightStdM: 0.03,
    widthStdM: 0.01,
    heightConfidence: 0.45,
    widthConfidence: 0.35,
  ),
  'bowl': ObjectSizePrior(
    className: 'bowl',
    typicalHeightM: 0.08,
    typicalWidthM: 0.18,
    heightStdM: 0.02,
    widthStdM: 0.04,
    heightConfidence: 0.50,
    widthConfidence: 0.55,
  ),
  'banana': ObjectSizePrior(
    className: 'banana',
    typicalHeightM: 0.18,
    typicalWidthM: 0.04,
    heightStdM: 0.03,
    widthStdM: 0.01,
    heightConfidence: 0.40,
    widthConfidence: 0.35,
  ),
  'apple': ObjectSizePrior(
    className: 'apple',
    typicalHeightM: 0.08,
    typicalWidthM: 0.08,
    heightStdM: 0.02,
    widthStdM: 0.02,
    heightConfidence: 0.45,
    widthConfidence: 0.45,
  ),
  'sandwich': ObjectSizePrior(
    className: 'sandwich',
    typicalHeightM: 0.08,
    typicalWidthM: 0.12,
    heightStdM: 0.02,
    widthStdM: 0.03,
    heightConfidence: 0.45,
    widthConfidence: 0.45,
  ),
  'orange': ObjectSizePrior(
    className: 'orange',
    typicalHeightM: 0.08,
    typicalWidthM: 0.08,
    heightStdM: 0.02,
    widthStdM: 0.02,
    heightConfidence: 0.45,
    widthConfidence: 0.45,
  ),
  'broccoli': ObjectSizePrior(
    className: 'broccoli',
    typicalHeightM: 0.15,
    typicalWidthM: 0.12,
    heightStdM: 0.04,
    widthStdM: 0.03,
    heightConfidence: 0.40,
    widthConfidence: 0.40,
  ),
  'carrot': ObjectSizePrior(
    className: 'carrot',
    typicalHeightM: 0.18,
    typicalWidthM: 0.03,
    heightStdM: 0.04,
    widthStdM: 0.01,
    heightConfidence: 0.40,
    widthConfidence: 0.35,
  ),
  'hot dog': ObjectSizePrior(
    className: 'hot dog',
    typicalHeightM: 0.12,
    typicalWidthM: 0.05,
    heightStdM: 0.03,
    widthStdM: 0.02,
    heightConfidence: 0.40,
    widthConfidence: 0.40,
  ),
  'pizza': ObjectSizePrior(
    className: 'pizza',
    typicalHeightM: 0.04,
    typicalWidthM: 0.30,
    heightStdM: 0.02,
    widthStdM: 0.05,
    heightConfidence: 0.40,
    widthConfidence: 0.50,
  ),
  'donut': ObjectSizePrior(
    className: 'donut',
    typicalHeightM: 0.04,
    typicalWidthM: 0.10,
    heightStdM: 0.02,
    widthStdM: 0.02,
    heightConfidence: 0.40,
    widthConfidence: 0.45,
  ),
  'cake': ObjectSizePrior(
    className: 'cake',
    typicalHeightM: 0.10,
    typicalWidthM: 0.20,
    heightStdM: 0.03,
    widthStdM: 0.04,
    heightConfidence: 0.45,
    widthConfidence: 0.45,
  ),
  'chair': ObjectSizePrior(
    className: 'chair',
    typicalHeightM: 0.90,
    typicalWidthM: 0.50,
    heightStdM: 0.08,
    widthStdM: 0.10,
    heightConfidence: 0.80,
    widthConfidence: 0.75,
  ),
  'couch': ObjectSizePrior(
    className: 'couch',
    typicalHeightM: 0.90,
    typicalWidthM: 2.00,
    heightStdM: 0.15,
    widthStdM: 0.40,
    heightConfidence: 0.60,
    widthConfidence: 0.65,
  ),
  'potted plant': ObjectSizePrior(
    className: 'potted plant',
    typicalHeightM: 0.70,
    typicalWidthM: 0.45,
    heightStdM: 0.20,
    widthStdM: 0.15,
    heightConfidence: 0.55,
    widthConfidence: 0.55,
  ),
  'bed': ObjectSizePrior(
    className: 'bed',
    typicalHeightM: 0.60,
    typicalWidthM: 2.00,
    heightStdM: 0.15,
    widthStdM: 0.40,
    heightConfidence: 0.55,
    widthConfidence: 0.60,
  ),
  'dining table': ObjectSizePrior(
    className: 'dining table',
    typicalHeightM: 0.75,
    typicalWidthM: 1.50,
    heightStdM: 0.12,
    widthStdM: 0.30,
    heightConfidence: 0.65,
    widthConfidence: 0.65,
  ),
  'toilet': ObjectSizePrior(
    className: 'toilet',
    typicalHeightM: 0.80,
    typicalWidthM: 0.45,
    heightStdM: 0.10,
    widthStdM: 0.08,
    heightConfidence: 0.70,
    widthConfidence: 0.65,
  ),
  'tv': ObjectSizePrior(
    className: 'tv',
    typicalHeightM: 0.60,
    typicalWidthM: 1.00,
    heightStdM: 0.12,
    widthStdM: 0.20,
    heightConfidence: 0.70,
    widthConfidence: 0.70,
  ),
  'laptop': ObjectSizePrior(
    className: 'laptop',
    typicalHeightM: 0.30,
    typicalWidthM: 0.35,
    heightStdM: 0.04,
    widthStdM: 0.05,
    heightConfidence: 0.75,
    widthConfidence: 0.80,
  ),
  'mouse': ObjectSizePrior(
    className: 'mouse',
    typicalHeightM: 0.04,
    typicalWidthM: 0.07,
    heightStdM: 0.01,
    widthStdM: 0.02,
    heightConfidence: 0.45,
    widthConfidence: 0.45,
  ),
  'remote': ObjectSizePrior(
    className: 'remote',
    typicalHeightM: 0.18,
    typicalWidthM: 0.05,
    heightStdM: 0.03,
    widthStdM: 0.02,
    heightConfidence: 0.45,
    widthConfidence: 0.45,
  ),
  'keyboard': ObjectSizePrior(
    className: 'keyboard',
    typicalHeightM: 0.04,
    typicalWidthM: 0.45,
    heightStdM: 0.02,
    widthStdM: 0.08,
    heightConfidence: 0.55,
    widthConfidence: 0.60,
  ),
  'cell phone': ObjectSizePrior(
    className: 'cell phone',
    typicalHeightM: 0.15,
    typicalWidthM: 0.07,
    heightStdM: 0.02,
    widthStdM: 0.02,
    heightConfidence: 0.80,
    widthConfidence: 0.75,
  ),
  'microwave': ObjectSizePrior(
    className: 'microwave',
    typicalHeightM: 0.30,
    typicalWidthM: 0.50,
    heightStdM: 0.08,
    widthStdM: 0.12,
    heightConfidence: 0.60,
    widthConfidence: 0.60,
  ),
  'oven': ObjectSizePrior(
    className: 'oven',
    typicalHeightM: 0.90,
    typicalWidthM: 0.60,
    heightStdM: 0.15,
    widthStdM: 0.10,
    heightConfidence: 0.65,
    widthConfidence: 0.60,
  ),
  'toaster': ObjectSizePrior(
    className: 'toaster',
    typicalHeightM: 0.20,
    typicalWidthM: 0.30,
    heightStdM: 0.05,
    widthStdM: 0.06,
    heightConfidence: 0.55,
    widthConfidence: 0.55,
  ),
  'sink': ObjectSizePrior(
    className: 'sink',
    typicalHeightM: 0.90,
    typicalWidthM: 0.60,
    heightStdM: 0.12,
    widthStdM: 0.10,
    heightConfidence: 0.65,
    widthConfidence: 0.60,
  ),
  'refrigerator': ObjectSizePrior(
    className: 'refrigerator',
    typicalHeightM: 1.80,
    typicalWidthM: 0.70,
    heightStdM: 0.20,
    widthStdM: 0.10,
    heightConfidence: 0.75,
    widthConfidence: 0.60,
  ),
  'book': ObjectSizePrior(
    className: 'book',
    typicalHeightM: 0.24,
    typicalWidthM: 0.16,
    heightStdM: 0.04,
    widthStdM: 0.03,
    heightConfidence: 0.55,
    widthConfidence: 0.55,
  ),
  'clock': ObjectSizePrior(
    className: 'clock',
    typicalHeightM: 0.30,
    typicalWidthM: 0.30,
    heightStdM: 0.08,
    widthStdM: 0.08,
    heightConfidence: 0.55,
    widthConfidence: 0.55,
  ),
  'vase': ObjectSizePrior(
    className: 'vase',
    typicalHeightM: 0.35,
    typicalWidthM: 0.20,
    heightStdM: 0.08,
    widthStdM: 0.05,
    heightConfidence: 0.60,
    widthConfidence: 0.55,
  ),
  'scissors': ObjectSizePrior(
    className: 'scissors',
    typicalHeightM: 0.20,
    typicalWidthM: 0.08,
    heightStdM: 0.03,
    widthStdM: 0.02,
    heightConfidence: 0.45,
    widthConfidence: 0.40,
  ),
  'teddy bear': ObjectSizePrior(
    className: 'teddy bear',
    typicalHeightM: 0.40,
    typicalWidthM: 0.30,
    heightStdM: 0.10,
    widthStdM: 0.08,
    heightConfidence: 0.55,
    widthConfidence: 0.55,
  ),
  'hair drier': ObjectSizePrior(
    className: 'hair drier',
    typicalHeightM: 0.25,
    typicalWidthM: 0.20,
    heightStdM: 0.06,
    widthStdM: 0.05,
    heightConfidence: 0.55,
    widthConfidence: 0.55,
  ),
  'toothbrush': ObjectSizePrior(
    className: 'toothbrush',
    typicalHeightM: 0.18,
    typicalWidthM: 0.02,
    heightStdM: 0.03,
    widthStdM: 0.01,
    heightConfidence: 0.45,
    widthConfidence: 0.35,
  ),
};
